name: Android Clone Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Change package name
      run: |
        grep -l -r 'jp.dip.muracoro.comittona' | xargs sed -i "s/jp.dip.muracoro.comittona/jp.dip.muracoro.comittona.by_8cAyqpVKio/g"
        grep -l -r '<string name="app_name">ComittoNxA</string>' | xargs sed -i "s/<string name=\"app_name\">ComittoNxA<\/string>/<string name=\"app_name\">ComittoNxD<\/string>/g"
        grep -l -r '<string name="app_launch_name">CNxA</string>' | xargs sed -i "s/<string name=\"app_launch_name\">CNxA<\/string>/<string name=\"app_launch_name\">CNxD<\/string>/g"
    - name: Build with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew clean assembleRelease
    - name: Sign APK
      id: sign_apk
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: ./app/build/outputs/apk/release/
        signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
        keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Release apk
        path: ${{steps.sign_apk.outputs.signedReleaseFile}}
